name: hejbej_se
description: Hejbej se – trasy v ČR s gamifikací.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^13.0.0
  pedometer: ^4.0.0
  shared_preferences: ^2.2.0
  google_maps_flutter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Atchivment_1km.png
    - assets/images/Atchivment_10km.png
    - assets/images/Atchivment_100km.png
    - assets/images/Atchivment_1000km.png
    - assets/images/Atchivment_10000km.png
    - assets/images/Atchivment_40000km.png
