name: hejbej_se
description: Hejbej se – trasy v ČR s gamifikací.
publish_to: "none"
version: 1.2.3+5

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^13.0.0
  pedometer: ^4.0.0
  shared_preferences: ^2.2.0
  google_maps_flutter: ^2.5.0
  google_maps_webservice: ^0.0.1-dev.0.1
  http: ^0.13.6
  pay: ^3.3.0
  flutter_secure_storage: ^8.0.0
  google_sign_in: ^6.0.0
  sign_in_with_apple: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/google_pay_config.json
    - assets/apple_pay_config.json
